CREATE TABLE USERS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL
);


CREATE TABLE PRODUCTS(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    base_price DECIMAL NOT NULL,
    tax_rate DECIMAL NOT NULL,
    status VARCHAR NOT NULL,
    inventory_quantity INT NOT NULL
);